### ISSUE TITLE
What is the correct hyperparameter adjustment when scaling training with multiple agents

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/ml-agents#1366]
I am training an environment with 16 agents and I would like to scale to 64 agents  (i.e. 4x)  to see if I can get a performance boost in training time.

How should one adjust the hyperparameters to get the same training results (or as close as possible)?

For example, these are my current settings:

```
LearnFromMocapBrain:
    normalize: true
    num_epoch: 3
    beta: 0.01
    time_horizon: 50
    max_steps: 1e6
    batch_size: 2048
    buffer_size: 10240
    summary_freq: 1000
    num_layers: 2
    hidden_units: 512
```

This will train for 16m time steps (1m * 16 agents) - so I should reduce `max_steps` to .25m to train for 16m time steps (.25m * 64 agents)

Should I also adjust `batch_size` and `buffer_size`?
