### ISSUE TITLE
BC followed by RL crashes

### ISSUE THREAD

**Issue by njustesen** [Unity-Technologies/ml-agents#1708]
I first trained a model using BC and then ran the following to continue training using PPO. 
`mlagents-learn config/trainer_config.yaml --run-id imitation-20e4 --train --load`
Is that even supported?

But it can't load the model:
```
INFO:mlagents.trainers:Loading Model for brain PyramidsLearning
INFO:tensorflow:Restoring parameters from ./models/imitation-20e4-0/PyramidsLearning/model-20001.cptk
2019-02-13 20:30:24.624956: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key dense_1/bias not found in checkpoint
```

My config/offline_bc_config.yaml 
```
default:
    trainer: offline_bc
    batch_size: 64
    summary_freq: 1000
    max_steps: 2.0e4
    batches_per_epoch: 10
    use_recurrent: True
    hidden_units: 128
    learning_rate: 20.0e-4
    num_layers: 2
    sequence_length: 32
    memory_size: 256
    demo_path: ./UnitySDK/Assets/Demonstrations/AgentRecording.demo
```

```
default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 2.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 32
    summary_freq: 1000
    use_recurrent: True
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
...
PyramidsLearning:
    use_curiosity: true
    summary_freq: 2000
    curiosity_strength: 0.01
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 64
    buffer_size: 2048
    beta: 1.0e-2
    max_steps: 2.0e4
    num_epoch: 3
```
