### ISSUE TITLE
Config Contains and Unknown Trainer Type

### ISSUE THREAD

**Issue by benmadinebuisness** [Unity-Technologies/ml-agents#1745]
Hi there,
Everytime I try and run the game an error in the console appears:
![capture](https://user-images.githubusercontent.com/46612079/53209409-4d05c800-3632-11e9-9539-cbe912c69608.JPG)

Don't have a clue whats happening because it was working earlier... 
Here is my trainer config code as well:

```
StudentPlayer:
    max_steps: 5.0e4
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 64
    num_layers: 2
```

Not sure what is happening, but any help is greatly appreciated!
