### ISSUE TITLE
Problem with Barracuda

### ISSUE THREAD

**Issue by SetoKaiba** [Unity-Technologies/ml-agents#1897]
I successfully trained my game and generated working nn models before.
But I just found it didn't working rencently.
Before it didn't work, I migrated the ml-agents python side to TF 2.0.
And I modify the RayPerception to use native collections to avoid the high GC Alloc per FixedUpdate.
I try to train it on TF 1.7.1 with RayPerception reverted and generate nn on TF 1.7.1.
But it still doesn't work.

<details>
<summary>
Here's the Exception:
</summary>

> ArgumentException: Off-axis dimensions must match
> Barracuda.TensorExtensions.Concat (Barracuda.TensorShape[] shapes, System.Int32 axis) (at <1071b9a446b04698af9605e3e272de23>:0)
> Barracuda.ModelAnalyzer.ListTemporaryTensorShapes (Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.Collections.Generic.IDictionary`2[System.String,Barracuda.TensorShape]& shapesByName) (at <1071b9a446b04698af9605e3e272de23>:0)
> Barracuda.ModelAnalyzer.TryGetOutputTensorShape (Barracuda.Model model, System.Collections.Generic.IDictionary`2[TKey,TValue] inputShapes, System.String output, Barracuda.TensorShape& shape) (at <1071b9a446b04698af9605e3e272de23>:0)
> Barracuda.ModelAnalyzer.TryGetOutputTensorShape (Barracuda.Model model, System.String output, Barracuda.TensorShape& shape) (at <1071b9a446b04698af9605e3e272de23>:0)
> Barracuda.ModelMetadataExtensions.GetShapeByName (Barracuda.Model model, System.String name) (at <1071b9a446b04698af9605e3e272de23>:0)
> MLAgents.InferenceBrain.BarracudaModelParamLoader.CheckOutputTensorShape (MLAgents.InferenceBrain.BarracudaModelParamLoader+ModelActionType isContinuous, System.Int32 modelActionSize) (at Assets/ML-Agents/Scripts/InferenceBrain/BarracudaModelParamLoader.cs:477)
> MLAgents.InferenceBrain.BarracudaModelParamLoader.GenerateChecks () (at Assets/ML-Agents/Scripts/InferenceBrain/BarracudaModelParamLoader.cs:187)
> MLAgents.InferenceBrain.BarracudaModelParamLoader.GetLoaderAndCheck (Barracuda.IWorker engine, Barracuda.Model model, MLAgents.BrainParameters brainParameters) (at Assets/ML-Agents/Scripts/InferenceBrain/BarracudaModelParamLoader.cs:47)
> MLAgents.LearningBrain.ReloadModel (System.Int32 seed) (at Assets/ML-Agents/Scripts/LearningBrain.cs:126)
> MLAgents.LearningBrainEditor.OnInspectorGUI () (at Assets/ML-Agents/Editor/LearningBrainEditor.cs:60)
> UnityEditor.UIElements.InspectorElement+<CreateIMGUIInspectorFromEditor>c__AnonStorey1.<>m__0 () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:441)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

</details>

Here's the nn file and the folders containing frozen graph and so on.
You can find the exception just by drag the nn model to the brain.
https://www65.zippyshare.com/v/e6b6QOJZ/file.html

**Comment by SetoKaiba** [comment]
It's caused by RNN. The problem have gone after "use recurrent: true" is removed.

<details>
<summary> Here's the hyperparameters causing the problem.</summary>

```
SenseiLearning:
    use_curiosity: true
    summary_freq: 2000
    curiosity_strength: 0.01
    curiosity_enc_size: 256
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 3
    use_recurrent: true
    sequence_length: 64
    memory_size: 256
```

</details>
