### ISSUE TITLE
No episode was completed since last episode

### ISSUE THREAD

**Issue by roboserg** [Unity-Technologies/ml-agents#2200]
So I am doing a simple flappy bird bot - https://puu.sh/DLHI2/b7060a2db2.png

An episode ends with Done() if the agent hits either the ground, ceiling, or the towers. Max steps in both the agent and the academy are set to 0. 

**1.** 
Yet for some reason after several hundred of thousands of training steps I start getting the "No episode was completed since last episode" - https://puu.sh/DLHFX/70c2074a80.png

Why does it happen and how do I fix it?

**2.** 
I am also unsure why the cumulative reward jumps like that - https://puu.sh/DLHMh/cd34aa1b6d.png
I tried gamma 0.9 / 0.95 / 0.999 and also different batch_size with 10 / 100 / 1000 (buffer_size was always 10x of the batch_size). Any tips or suggestions of why it jumps like that and how to improve the learning?  The variance is too high, the agent does only 7-30 towers on average. It should fly almost indefinitely

ps. rewards are -1 when hitting an obstacle. +1 when flying through the tower and +0.001 at every step alive. Two discreet actions, 0 do nothing and 1 jump.

pss. training config:

```
default:
    max_steps: 1000000
    batch_size: 1000
    buffer_size: 10000
    gamma: 0.9
    epsilon: 0.2
    trainer: ppo
    beta: 5.0e-3
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 500
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
```
