### ISSUE TITLE
Imitation Learning with multiple brain

### ISSUE THREAD

**Issue by djsdvg** [Unity-Technologies/ml-agents#2445]
Is there a way to training two brain simultaneously with Imitation Learning ?
I have two different demonstration, one for each different brain in the scene but i don't know how to use them when training.
I saw that i can pass one demonstration using the .yaml config file but i didn't found how to pass two of them.

**Comment by vincentpierre** [comment]
If you are trying to train two brains with two demos at the same time (either offline BC or GAIL), you need to specify the demo files for each of the brains : 

```
default:
    <default parameters>
TheFirstBrainLearning:
    trainer: offline_bc
    demo_path: <first_demo>.demo
TheSecondBrainLearning:
    trainer: offline_bc
    demo_path: <second_demo>.demo
```

If you want to train a single Brain with two demo files, we do not currently support this use case.
