### ISSUE TITLE
AgentAction sometimes ignore masked actions and cause invalid agent actions.

### ISSUE THREAD

**Issue by CharlieReece** [Unity-Technologies/ml-agents#2769]
**Describe the bug**
"Sometimes", AgentAction ignores masked actions while using Discrete Vector Space and on demand Decision Requests which causes invalid agent actions and corrupts learning process. I noticed this in my own project and tried to replicate it in original Unity examples; I was able to modify "Basic" example to replicate this problem there too. 

**To Reproduce**
1. Open ML-Agents > Examples > Basic > Scenes >Basic
2. Edit Basic/Scripts/BasicAgent.cs and add the following inside CollectObservations function after `AddVectorObs(m_Position, 20);`:
```
        var maskList =new List<int>();
        for(int i = 3; i < 210;++i) {
            maskList.Add(i);
        }
        SetActionMask(0, maskList);

        var dummyObsList = new List<float>();
        for (int i = 0; i < 52; ++i) {
            dummyObsList.Add(i);
        }
        AddVectorObs(dummyObsList);
```
3. Add the following to AgentAction function, after `var movement = (int)vectorAction[0];`:
`        Debug.Assert(movement < 3, "Action was called eventhough it was masked."+movement);`
4. Save the file.
5. Change brain parameters (BasicLearning):
- Vector Size: 72
- Branch 0 Size: 210
6. Change Academy's Training Configuration:
- Quality: 0
- Target Frame Rate: -1
7. Change config.yaml:
- Rename **BasicLearning** to **BasicLearningIgnored** so the following **modified** default one can be used:
```
    trainer: ppo
    batch_size: 10
    beta: 5.0e-3
    buffer_size: 100
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 15.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
```
8. Run ml-agents: `mlagents-learn config/config.yaml --run-id=basicx3 --train`

**Console logs / stack traces**
You will *eventually see the Assertion Line you added in BasicAgent.cs and that must not normally happen as all those actions must have been masked.
* If you don't see it first, re-run and you should see it. Somehow masked actions are still called even if this happens rarely. Even if it is rare, it is enough to corrupt the learning process and I am always able to replicate this problem.

**Environment (please complete the following information):**
- OS + version: Mac OS Catalina 10.15 (19A602)
- ML-Agents version_: 0.10.1
- Unity version: 2019.2.9.f1
- Tensorflow: 1.15rc2 (also 1.14.0)

**UPDATE:** Starting from 26 actions ( Branch size: 26 ), this problem occurs. No need to above extra dummy observation lines, etc. I did not replace them as they may still give ideas. The step 2 above can be replaced with the following, other steps except the branch size and reverted observation space size(20), remain the same:
```
 public override void CollectObservations() {
        AddVectorObs(m_Position, 20);
        SetActionMask(0, new int[] { 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 });
    }
```

I also debugged at that moment to check ActionMasker's current state and I perfectly see the masked values there. So, somehow, AgentAction is still called with an action that is clearly marked as masked. I tried with lower branch sizes and it does not "seem like" there will be a problem, though I cannot guarantee, but over >= 26 I always get the assertion at a certain point.
