### ISSUE TITLE
Agent won't search for objects and only rotates

### ISSUE THREAD

**Issue by sekne18** [Unity-Technologies/ml-agents#3189]
So I can't figure out whats wrong... I start to train my agent and soon it learns to pick up eggs. I use curriculum and in the beginning area spawns 5 egg, which agent has to collect and is successful until lesson upgrades and obstcales comes. From here on agent only learns to spin, except if the egg is not behind the obsticale, then he will catch it. Im giving him reward when he touches the egg and a little bonus on the last one. Punishment is given when he hits the wall and while he is moving . I tried configuring` trainer_config.yaml `and `.json` file, but no success. Here is some of my code for observations:

CollectObservations:
```
AddVectorObs((egg.transform.position - transform.position).normalized);
AddVectorObs(transform.forward);
float rayDistance = 20f;
float[] rayAngles = { 30f, 60f, 90f, 120f, 150f };
string[] detectableObjects = { "egg", "wall" };
AddVectorObs(rayPerception.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
```
trainer_config(currently) file:
```
RabbitLearning:
    normalize: true
    batch_size: 128
    hidden_units: 256
    beta: 1.0e-2
    buffer_size: 1024
    max_steps: 1.0e6
    summary_freq: 5000
    time_horizon: 128
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
```
RabbitLearning.json file:
{ 
  "measure": "reward",
  "thresholds": [ -0.1, 0.7, 1.7, 1.7, 1.7, 1.7, 1.7, 2.7 ],
  "min_lesson_length": 80, 
  "signal_smoothing": true,
  "parameters": {
    "egg_Number": [ 5.0, 4.0, 3.0, 4.0, 3.0, 2.0, 4.0, 3.0, 1.0 ],
    "obstcales": [ 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0 ]
  }
}

Here's also screenshot from recent training:
![statistics-rl-unity](https://user-images.githubusercontent.com/25244849/72048652-8a605c00-32bd-11ea-8736-9d1a68106b1d.PNG)

And that's my agent area:
![agentarea](https://user-images.githubusercontent.com/25244849/72048949-3ace6000-32be-11ea-8e43-7c4f5609a918.PNG)

I pretty new to ml agent so any advice would be prefect. Thank you.
