### ISSUE TITLE
KeyError when training with Curriculum

### ISSUE THREAD

**Issue by nic126** [Unity-Technologies/ml-agents#3337]
hey, guys,  
I'm just trying to get my agent with curriculum training up and running.
In my scene I have an agent and a NavMeshAgent.

To start the training, I use the command line from the docs: 
mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/chaser/ --run-id=chaser-curriculum_test --train

In the trainer_config.yaml I have defined the following parameters:
```yaml
ChaserLearning:
    use_curiosity: true
    summary_freq: 1000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_unity: 256
    beta: 1.0e-2
    max_steps: 1.0e6
  ```
and I have created a folder in \ml-agents\config\curricula\ named chaser. In it is the file ChaserLearning.json. 
The file has the following values:
```
{
    "measure" : "reward",
    "thresholds : [-0.1, 0.7, 1, 1.5, 1.7, 2],
    "min_lesson_length" : 80,
    "signal_smoothing" : true, 
    "parameters" : 
    {
        "speedMultiplicator" : [0.5, 0.75, 0.9, 1.0, 1.25, 1.5, 1.75]
    }
}
```
The BehaviourParameter Script in the Unity Editor is named chaser-Curriculum_test01
When I start the training, I get the following error in the shell:

KeyError: 'chaser-Curriculum_test01'

I have attached a screenshot of the shell below.
Did I make a mistake somewhere, or is it because of the ML-Agents version?
![Inkedshell_LI](https://user-images.githubusercontent.com/35842664/73641490-63a10580-4670-11ea-9e53-750b187b48e2.jpg)

thanks in advance
