### ISSUE TITLE
Ability to use previously trained models with GAIL

### ISSUE THREAD

**Issue by AcelisWeaven** [Unity-Technologies/ml-agents#3419]
**Is your feature request related to a problem? Please describe.**
(not a real story)
Let's admit I've got a great model that took weeks to train. It has 10 hidden layers of 1024 units.
Inference will probably be really slow.

**Describe the solution you'd like**
Let's say I want to reduce my model size to a single hidden layer of 512 units. I've would have a gail_config.yaml looking like that:
```
MyEnv:
    num_layers: 1
    hidden_units: 512
    reward_signals:
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            model_path: MyEnv.nn
```
Would it be possible to use GAIL to be able to create a lighter (and faster) model for inference, instead of retraining from scratch?
