### ISSUE TITLE
Different behaviour between frozen and live model

### ISSUE THREAD

**Issue by Alexander-Bakogeorge** [Unity-Technologies/ml-agents#3780]
**Describe the bug**
Hi, I'm trying to train 2 agents to balance a weight on a small planet. So fair my trainings have been successful, but I've noticed an odd behaviour. When I run inference through python (mlagents-learn, sans --train), my agents move more sporadically than their exported .nn file counterparts. I've attached two gifs below to illustrate (both are at 10 timescale, red balls are agents, white ball is the weight).

**Screenshots**
.nn files
![gif1](https://user-images.githubusercontent.com/25420678/79276461-0ac2ca00-7e76-11ea-8803-11f4f37f8338.gif)
Python
![gif2](https://user-images.githubusercontent.com/25420678/79276465-0f877e00-7e76-11ea-94ea-3196e99959b0.gif)

**Environment**
- Windows 10 Pro - 10.0.18362 Build 18362
- ML-Agents v1.14.0
- TensorFlow 2.0.1
- Custom environment, but I've included a pastebin of the agent and planet code [here](https://pastebin.com/889BJm5y)

**Comment by andrewcoh** [comment]
Hi @Alexander-Bakogeorge 

Can you share your trainer configuration too?

**Comment by Alexander-Bakogeorge** [comment]
@andrewcoh 

```
    trainer: ppo
    batch_size: 128
    beta: 5.0e-3
    buffer_size: 1024
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 1.0e7
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
```
