### ISSUE TITLE
mlagents.trainers.exception.TrainerConfigError: Trainer config must have either a "default" section, or a section for the brain name (3DBall).

### ISSUE THREAD

**Issue by Kyunghyunn** [Unity-Technologies/ml-agents#3957]
Hi, all.

I'm trying to follow "Getting started guide".
(https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started.md)

When I train the environment and run **mlagents-learn config/ppo/3DBall.yaml --run-id=first3DBallRun,**

Error suggested **mlagents.trainers.exception.TrainerConfigError: Trainer config must have either a "default" section, or a section for the brain name (3DBall). See config/trainer_config.yaml for an example.**

I cloned ml-agents master version which has config/ppo/3DBall.yaml

Does anyone how to resolve this problem?

Thank you!

**Comment by awjuliani** [comment]
Hi @Kyunghyunn 

I just tried the command you used from the `master` branch and did not get this error. Could you try pulling the latest master release, or using the `release-1` version? It is likely that you may have config files and/or code that is not all up to date.

**Comment by Kyunghyunn** [comment]
Thanks for your reply @awjuliani 

I'm using the latest master release because the release-1 version doesn't have the file, config/ppo/3DBall.yaml. I checked the trainer_config.yaml from release-1 version, but I couldn't find any solution. It seems like 3DBall.yaml includes a section for the brain name (3DBall). The problem still happens.
This is the entire log.

Traceback (most recent call last):
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in _create_trainer_and_manager
    trainer = self.trainers[brain_name]
KeyError: '3DBall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kyunghyunkim\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kyunghyunkim\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\KyunghyunKim\anaconda3\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 554, in main
    run_cli(parse_command_line())
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 550, in run_cli
    run_training(run_seed, options)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 407, in run_training
    tc.start_learning(env_manager)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 227, in start_learning
    self._create_trainers_and_managers(env_manager, new_behavior_ids)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 213, in _create_trainers_and_managers
    self._create_trainer_and_manager(env_manager, behavior_id)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 177, in _create_trainer_and_manager
    trainer = self.trainer_factory.generate(brain_name)
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_util.py", line 61, in generate
    self.multi_gpu,
  File "c:\users\kyunghyunkim\anaconda3\lib\site-packages\mlagents\trainers\trainer_util.py", line 100, in initialize_trainer
    f'Trainer config must have either a "default" section, or a section for the brain name ({brain_name}). '
mlagents.trainers.exception.TrainerConfigError: Trainer config must have either a "default" section, or a section for the brain name (3DBall). See config/trainer_config.yaml for an example.

**Comment by henryyuanheng-wang** [comment]
I'm having the same issue with the same error messages using the latest master branch. Both training using Editor and passing environment file fail. Thanks for the reply in advance.

**Comment by c0deminded** [comment]
I also faced this issue when doing [this](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md) guide.
I'v just compared the **rollerball_config.yaml** and **trainer_config.yaml** which is used to train example models and figured out some differences. I've reformatted it like **trainer_config.yaml** and it worked!

So my config file now looks like this.
```
default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

RollerBall:
    batch_size: 10
    buffer_size: 100
    memory_size: 128

```
