### ISSUE TITLE
Error: The option curriculum was specified in your YAML file, but is invalid.

### ISSUE THREAD

**Issue by nntsrb** [Unity-Technologies/ml-agents#4439]
I have this error when I tried to train with the file below. It used to work before, but now it seems there are some problem with the curriculum file.

```
behaviors:
  TileBaseISO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

curriculum:
  TileBaseISO:
    measure: reward
    thresholds: [-1.8, -1.2, -0.5, 0.5, 1.2, 1.8]
    min_lesson_length: 80
    signal_smoothing: true
    parameters:
      mosquito_count: [8.0, 7.0, 6.0, 5.0, 4.0, 3.0]
```
