### ISSUE TITLE
Behavioural Cloning with Gail agent behave wired 

### ISSUE THREAD

**Issue by shohanulka** [Unity-Technologies/ml-agents#5316]
I have been trying to reproduce the similar behavior by following this tutorial [https://youtu.be/2X5m_nDBvS4](https://youtu.be/2X5m_nDBvS4) I am using the behavioral cloning with gail but after lots of training the agent is not performing as expected. I am using discrete action for autonomous agent e.g: car and trying to make the behave exactly like the demonstration, I am also using the same time-scale in training and game. Someone please assist me, this is my first approach to use ML Agent toolkit. 

```
default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-4
    buffer_size: 10240
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 9.0e7
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    time_horizon: 128
    hidden_units: 512
    reward_signals:
        extrinsic:
            strength: 0.01
            gamma: 0.99
       
RaceAgent:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-4
    buffer_size: 10240
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 50000000
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    time_horizon: 128
    hidden_units: 512
    behavioral_cloning:
        demo_path: expert_6.demo
        strength: 1.0
        steps: 100000
    reward_signals:
        extrinsic:
            strength: 0.1 #0.01
            gamma: 0.99
        curiosity:
            strength: 0.02 #0.02
            gamma: 0.99 #0.90
            encoding_size: 256
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            demo_path: expert_6.demo
```

- Unity Version: 2019.4.2
- OS + version: MacOs
- _ML-Agents version_: 1.0.6
