### ISSUE TITLE
Curriculum progress min_lesson_length may have some bug.

### ISSUE THREAD

**Issue by nathan60107** [Unity-Technologies/ml-agents#5400]
**Describe the bug**
When I am trying to set measure to `progress` in Curriculum, there is something strange.

**To Reproduce**
If I set max_steps as 50000, threshold as 0, and min_lesson_length as 100. Just like
```
...
    max_steps: 50000
...
    curriculum:
      - name: MyFirstLesson
        completion_criteria:
          measure: progress
          behavior: Ghost
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0
        value: 0.0
      - name: MySecondLesson
      ...
```
It will be MySecondLesson when the console shows Step: 2000.
And if I change min_lesson_length as 1000, it will be MySecondLesson when the console shows Step: 20000. Is that a bug or a normal situation?
In `Training-ML-Agents.md`, it says "The minimum number of episodes" for min_lesson_length. Are "episodes" mean step? If so, I think it should not use episodes and should use steps just like other descriptions to avoid misleading.

**Console logs / stack traces**
**Screenshots**
If cannot reproduce I will provide tensorboard file.

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.24f1
- OS + version: Windows 10
- _ML-Agents version_: release15
- _Torch version_: 1.7.1+cu110
- _Environment_: 

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
