### ISSUE TITLE
Use curriculum and agent group at the same time

### ISSUE THREAD

**Issue by nathan60107** [Unity-Technologies/ml-agents#5485]
**Is your feature request related to a problem? Please describe.**
I made an asymmetric game that has one ghost and one human, and a ghost tries to catch a human, the human need to run away. Curriculum works well at that time. Now, I change the number of humans to 2, and they need to work together to solve some missions, so I register them as a group. But I find that I cannot set group reward as the `measure` of `completion_criteria` in `curriculum`. And it seems nobody has asked this question before.
Is there any way to use group reward as the `measure` now? If not, I have to keep use agent reward as `measure`, or control the curriculum by myself.

**Describe the solution you'd like**
### Method 1
Let users choose group_reward as `measure`. Since groups is not on the config file so we can only choose behavior as the target of measure. An example as below:
```yaml
- name: MyFirstLesson
    completion_criteria:
      measure: group_reward # a new measure
      behavior: Human
      signal_smoothing: true
      min_lesson_length: 100
      threshold: 0.2
    value: 0.0
```
But there is a big problem behind this method. Human agents can join different groups at the same time. For example, Human1 and 2 join group A, and Human 3 and 4 join group B, Ghost1 joins group C. In this situation, config above will take all Human1234's mean group reward as `measure` rather than only Humans of group A. And still no way to only choose group A as measure target. It is the same way TensorBoard shows group rewards, all Human agents share mean group rewards. So it might be a way to measure group reward.

**Describe alternatives you've considered**
### Method 2
We can improve the function of the curriculum. For example, try to use C# code as a criteria. If we have yaml as:
```yaml
environment_parameters:
  my_envpara:
    curriculum:
      - name: MyFirstLesson
...
```
and if users call `Academy.Instance.CompletionCriteria("my_envpara")`, then `my_envpara` will move to next lesson. This allows users to define curriculum more flexibly. But this also needs the ability to access mean reward of behavior and mean reward of agent group in C# code for users. There might be a lot of work. In that way, users can get the mean reward of group A. If the mean reward is high enough, users call `CompletionCriteria`.

**Additional context**
I know that we always want the reward of agents higher. But sometimes we may need rewards to be lower in some situations. For example:
```yaml
environment_parameters:
  my_envpara:
    curriculum:
      - name: MyLesson1
      - name: MyLesson2
      - name: MyLesson3
...
```
In the lesson1 I let Ghost learn to catch Humans, so the mean reward of Ghost will go higher. If the mean reward of Ghost is high enough, there goes to lesson2. In lesson2, I will change some environments to let Human learn to run away. The criteria of lesson2 can be the mean reward of Ghost lower enough, or the mean reward of Human higher enough. But there might be some situations that I cannot use the reward of Human as criteria.
What I want to express is, criteria of curriculum need more flexibility. So users can build a more complex curriculum.

### A bug report
And there is also a bug in the curriculum. When I set yaml as:
```yaml
- name: MyFirstLesson
    completion_criteria:
      measure: reward # a new measure
      behavior: Ghost
      signal_smoothing: true
      min_lesson_length: 100
      threshold: -0.75
    value: 0.0
```
and I fix the reward of Ghost as -1, criteria will be satisfied and go to next lesson. But when I set the threshold as -0.74, it will not. For some reason, reward α can satisfy the threshold of 0.75α, and α must be negative.
When I fix the mean reward as 0, threshold 0 will not be satisfied and threshold -0.99 will be satisfied. So there is no problem when the mean reward >=0. If the mean reward <0, it can complete the criteria even it is lower than the threshold. Is that a bug or something wrong with my operation?

Here is two real example:
#### case1:
```yaml
course_stage:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 5277
          value: 0.0
      name: Lesson0 (Ghost learn to catch human, freeze human)
      completion_criteria:
        behavior: Ghost
        measure: reward
        min_lesson_length: 1000
        signal_smoothing: true
        threshold: -0.7499 # <- difference
        require_reset: false
```
![圖片](https://user-images.githubusercontent.com/18046878/127831766-7a723ab0-a6b2-4225-9cae-1b4405929b63.png)
Almost all mean reward of Ghost is -1, and the threshold is -0.7499, but it goes to the next lesson at step 20k, which is min_lesson_length.

#### case2:
```yaml
curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 4928
          value: 0.0
      name: Lesson0 (Ghost learn to catch human, freeze human)
      completion_criteria:
        behavior: Ghost
        measure: reward
        min_lesson_length: 1000
        signal_smoothing: true
        threshold: -0.74 # <- difference
        require_reset: false
```
![圖片](https://user-images.githubusercontent.com/18046878/127831946-61258b46-d83f-4649-91f2-f583a1fbc196.png)
All mean reward of Ghost is -1 or even higher, and the threshold is -0.74, but it doesn't go to next lesson until 300k.
This bug makes me cannot build a correct curriculum, which lets Ghost train until the mean reward of Ghost >=0.8 and go to the next lesson.

It is because the code [here](https://github.com/Unity-Technologies/ml-agents/blob/d199d01b01746fd29b40c5a92fa15a12400308db/ml-agents/mlagents/trainers/settings.py#L506). The initial value of smoothing is 0 and the initial value of my measure is -1, 0.25\*0+0.75\*(-1)=>-0.75, the value becomes larger and will go to the next lesson. If the initial value of my measure is 1, 0.25\*0+0.75\*1=>0.75, the value becomes smaller, so no bug here. That is why only negative values cause this bug. I think there is no need to use smoothing since it is a mean value, so you can just remove smoothing option or renew the way it get its initial value.
