### ISSUE TITLE
Continuous action - input is always zero while training

### ISSUE THREAD

**Issue by Nirav-Madhani** [Unity-Technologies/ml-agents#5505]
**Describe the bug**
I am using ml agents mlagents==0.27.0 , 
The continuous action input is always 0 while training. 

**To Reproduce**
Use Below Configuration and try training any model
```
absl-py==0.13.0
attrs==21.2.0
cachetools==4.2.2
cattrs==1.5.0
certifi==2021.5.30
chardet==4.0.0
cloudpickle==1.6.0
google-auth==1.32.0
google-auth-oauthlib==0.4.4
grpcio==1.38.1
h5py==3.2.1
idna==2.10
Markdown==3.3.4
mlagents==0.27.0
mlagents-envs==0.27.0
numpy==1.20.3
oauthlib==3.1.1
Pillow==8.2.0
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pypiwin32==223
pywin32==301
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.16.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
torch==1.9.0
torchvision==0.10.0
typing-extensions==3.10.0.0
urllib3==1.26.5
Werkzeug==2.0.1

```
**Console logs / stack traces**
Not Applicable

**Screenshots**
Not Applicable

**Environment (please complete the following information):**
- Unity Version:  Unity 2021.1.6f1
- OS + version: Windows 10
- _ML-Agents version_: 0.27.0 
- _Torch version_: Version: 1.9.0  
- _Environment_: As mentioned above

**Comment by andrewcoh** [comment]
Hi @Nirav-Madhani 

Can you verify that this does not happen on one of our example environments or have you verified that it _does happen?_  Are you seeing NaNs in the tensorboards?

**Comment by Nirav-Madhani** [comment]
It does work on example environments. 

For my environment,
I checked training_status.json , timers.json and tensorboard as well.
No NaN anywhere.

BTW here is my config file if it can help identify any peoblem
```
behaviors:
  TRC:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2560
      learning_rate: 0.003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
      gail:
        strength: 0.8
        demo_path: Project\Assets\T-Demos\D1.demo
    keep_checkpoints: 5
    max_steps: 400000
    time_horizon: 64
    behavioral_cloning:
      demo_path: Project\Assets\T-Demos\D1.demo
      strength: 0.7
    summary_freq: 100
```

The command I used:
```
mlagents-learn config\ppo\TRC.yaml --run-id=TRC --resume  --time-scale 5
```

I have 4 camera input and 1 int variable as observation.
