### ISSUE TITLE
vis_encoder_type is overridden

### ISSUE THREAD

**Issue by Simple2Sample** [Unity-Technologies/ml-agents#5614]
**Describe the bug**
I'm having issues where I the vis_encode_type defaults to simple regardless of what option or size of the neural network I use. I'm trying to make it create a fully_connected network, but ML-agents simply ignores the parameter for some reason. As fully_connected does not have a minimum size, it should not in my opinion override my vis_encode_type setting

The ML.yaml file I used:
```
  ML:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 32768
      learning_rate: 2.5e-3
      learning_rate_schedule: constant
      beta: 1e-2
      epsilon: 0.1
      lambd: 0.98
      num_epoch: 2
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      vis_encoder_type: fully_connected
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.999
      curiosity:
        strength: 0.01
        gamma: 0.8
    max_steps: 3e7
    time_horizon: 32
    summary_freq: 50000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: true
    init_path: null
```

What the terminal outputs. Notice the change in vis_enode_type:
```
[INFO] Hyperparameters for behavior name ML:
        trainer_type:   ppo
        hyperparameters:
          batch_size:   1024
          buffer_size:  32768
          learning_rate:        0.0025
          beta: 0.01
          epsilon:      0.1
          lambd:        0.98
          num_epoch:    2
          learning_rate_schedule:       constant
        network_settings:
          normalize:    False
          hidden_units: 32
          num_layers:   2
          vis_encode_type:      simple
          memory:       None
          goal_conditioning_type:       hyper
        reward_signals:
          extrinsic:
            gamma:      0.999
            strength:   1.0
            network_settings:
              normalize:        False
              hidden_units:     128
              num_layers:       2
              vis_encode_type:  simple
              memory:   None
              goal_conditioning_type:   hyper
          curiosity:
            gamma:      0.8
            strength:   0.01
            network_settings:
              normalize:        False
              hidden_units:     128
              num_layers:       2
              vis_encode_type:  simple
              memory:   None
              goal_conditioning_type:   hyper
            learning_rate:      0.0003
            encoding_size:      None
        init_path:      None
        keep_checkpoints:       5
        checkpoint_interval:    500000
        max_steps:      30000000
        time_horizon:   32
        summary_freq:   50000
        threaded:       True
        self_play:      None
        behavioral_cloning:     None
```
**Environment:**
- Unity Version: [Unity 2021.1.26f1]
- OS + version: [Windows 10]
- _ML-Agents version_: 0.27.0
