### ISSUE TITLE
Cannot reprodue the Bullet Hell example

### ISSUE THREAD

**Issue by chenzhutian** [Unity-Technologies/ml-agents#5701]
**Describe the bug**
Hi, I try to reproduce the dodge bullet example presented in this [release note](https://blog.unity.com/technology/ml-agents-v20-release-now-supports-training-complex-cooperative-behaviors). I get the code from the [dev-bullet-hell](https://github.com/Unity-Technologies/ml-agents/tree/develop-bullet-hell/Project/Assets/ML-Agents/Examples/Bullet) branch. The pretrained model works well  and I can run the training code to start the training. However, I just cannot get the expected reward (the max rewards should be ~5.0, but I only got ~0.2 after training). Can you please help? thanks!

![image](https://user-images.githubusercontent.com/3315274/152806576-8058fcef-58e7-4efe-a974-e4cd4d1b9ca1.png)

I used the training config from [here](https://github.com/Unity-Technologies/ml-agents/blob/bullet-hell-barracuda-test-1.3.1/config/ppo/Bullet.yaml)
```yaml
behaviors:
  Dodge:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 100000
    threaded: true
```
