### ISSUE TITLE
ppo training file not recognized when attempting to train crawler example. "The option Crawler was specified in your YAML file, but is invalid."

### ISSUE THREAD

**Issue by kryptoish** [Unity-Technologies/ml-agents#5813]
I was attempting to use the crawler example in Unity and had some trouble training the model using the given ppo yaml file. This was all done after I moved the prefab to a new scene and removed its pre-trained brain (so i can train it). I did not change any of the code that was given so far.

**To Reproduce**
First I used this ppo file:
```behaviors:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 30000

Crawler:
   batch_size: 2048 
   memory_size: 128
   buffer_size: 20480
```
The scene and unity package is this one (ppo file and scene included):
[Final-Quadropedexport1.zip](https://github.com/Unity-Technologies/ml-agents/files/10018880/Final-Quadropedexport1.zip)

From here I used anaconda prompt and entered the venv then followed with the training syntax:
mlagents-learn "config\crawler.yaml" --run-id=crawlertest1

After that the error pops up:
![image](https://user-images.githubusercontent.com/69884464/202108615-0ed42503-fe61-44dc-b3bf-0624bbb498b5.png)

And I have tried reformatting the file already but I did not work. ( i dont have the exact file but it looks like this):
```
behaviors:
  3DBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
```
With some differences

**Environment (please complete the following information):**
Unity Version: Unity 2021.3.8f1
OS + version: Windows 10 pro
ML-Agents version: ML-agents v0.29.0 
Torch version: 1.12.1
Environment: Python 3.7.13

One more note is that when I tried running the pretrained model given by the example it does not work and just flops to the ground and shows an warning:
![image](https://user-images.githubusercontent.com/69884464/202109827-734f60f3-7358-46fa-bf09-030457161fa9.png)
![image](https://user-images.githubusercontent.com/69884464/202110099-a45f228a-505e-4be8-ac04-4e97da48d19b.png)
Just sits there and I don't know why
